<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EchoVersion>1.0.0-master.378</EchoVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.14.28" />
    <PackageVersion Include="AsmResolver.DotNet" Version="6.0.0" />
    <PackageVersion Include="Echo.Ast" Version="$(EchoVersion)" />
    <PackageVersion Include="Echo.Platforms.AsmResolver" Version="$(EchoVersion)" />
    
    <GlobalPackageReference Include="PolySharp" Version="1.16.0" />
  </ItemGroup>
</Project>
