<Project>
    <PropertyGroup>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <PolySharpUseEmbeddedAttributeForGeneratedTypes>false</PolySharpUseEmbeddedAttributeForGeneratedTypes>
    </PropertyGroup>
</Project>
