<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.14.8" />
    <PackageVersion Include="AsmResolver.DotNet" Version="6.0.0-beta.2" />
    <PackageVersion Include="Echo.Ast" Version="1.0.0-master.353" />
    <PackageVersion Include="Echo.Platforms.AsmResolver" Version="1.0.0-master.353" />
    <PackageVersion Include="System.Reflection.Metadata" Version="9.0.9" />
    
    <GlobalPackageReference Include="PolySharp" Version="1.15.0" />
  </ItemGroup>
</Project>
